### ISSUE TITLE
Can not move the app window to my second display

### ISSUE THREAD

**Issue by MeowKJ** [UnnamedOrange/osu-kps#8]
Can not move the app window to my second display
i record a gif
![](https://user-images.githubusercontent.com/65823167/161965238-172dd19f-19fc-46f3-8fbc-897f6d8d0f48.gif)

**Comment by UnnamedOrange** [comment]
Thank you for your report. Till now osu-kps is not designed for multi-monitors because I have only one screen. This issue can be suppressed as a temporary fix by commenting the line in main.cpp below.

https://github.com/UnnamedOrange/osu-kps/blob/b893d1fb75f001ac6bb5951182590dc0096a1e0e/osu-kps/main.cpp#L57

**Comment by UnnamedOrange** [comment]
Try out [beta-2022.407](https://github.com/UnnamedOrange/osu-kps/releases/tag/beta-2022.407).
